#!/bin/bash
# Author:  a950216t <a950216t AT gmail.com>
# Blog:  http://blog.myxnova.com
#
# This script's project home is:
#       http://blog.myxnova.com/lampd.html
#       https://github.com/a950216t/lampd

# Check if user is root
[ $(id -u) != "0" ] && echo "Error: You must be root to run this script" && exit 1

export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
clear
printf "
#######################################################################
#    LNMP/LAMP/LANMP for CentOS/RadHat 5+ Debian 6+ and Ubuntu 12+    #
# For more information please visit http://blog.myxnova.com/lampd.html  #
#######################################################################
"
[ ! -e "src" ] && mkdir src
cd src
. ../functions/download.sh

if [ -n "`grep 'CentOS release 6' /etc/redhat-release`" -a `getconf LONG_BIT` = "64" ];then
		echo -e "\033[31mYou can install this Desktop. \033[0m"
else
        echo -e "\033[31mDoes not support this OS, Please contact the author! \033[0m"
        exit 1
fi

cat >/etc/selinux/config <<EOF
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
# enforcing - SELinux security policy is enforced.
# permissive - SELinux prints warnings instead of enforcing.
# disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of these two values:
# targeted - Only targeted network daemons are protected.
# strict - Full SELinux protection.
SELINUXTYPE=targeted
EOF

cat >/etc/sysconfig/i18n <<EOF
LANG="en_US.UTF-8"
SUPPORTED="zh_TW.UTF-8:zh_TW.Big5:zh_TW:zh:en_US.UTF-8:en_US:en"
SYSFONT=latarcyrheb-sun16
EOF

yum -y update
wget -c http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
rpm -ivh epel-release-6-8.noarch.rpm
yum -y groupinstall "Development Tools"
yum -y groupinstall "Chinese Support"
yum -y groupinstall "Xfce"
yum -y install "@Chinese Support"
yum -y groupremove "Web Server"
yum -y install xfce* tigervnc tigervnc-server firefox terminal filezilla
service NetworkManager stop
chkconfig NetworkManager off
cd /etc/yum.repos.d/
wget -c http://geekery.altervista.org/geekery-el6-x86_64.repo
yum -y install transmission*
yum -y update --setopt=protected_multilib=false

#Set timezone
rm -rf /etc/localtime
ln -s /usr/share/zoneinfo/Asia/Taipei /etc/localtime

yum install -y ntp
ntpdate -d time.stdtime.gov.tw
date

vncserver
service vncserver stop
pkill -9 vnc
rm -rf /tmp/.X1*

cd /root/
wget -c http://fpdownload.macromedia.com/get/flashplayer/pdc/11.2.202.425/install_flash_player_11_linux.x86_64.tar.gz
tar zxvf install_flash_player_11_linux.x86_64.tar.gz
mkdir -p ~/.mozilla/plugins/
cp libflashplayer.so ~/.mozilla/plugins/

echo 'VNCSERVERS="1:root"' >> /etc/sysconfig/vncservers
echo 'VNCSERVERARGS[1]="-geometry 1024x768"' >> /etc/sysconfig/vncservers
/etc/init.d/vncserver restart
cat >/root/.vnc/xstartup <<EOF
#!/bin/sh
source /etc/sysconfig/i18n
/usr/bin/startxfce4
EOF

/etc/init.d/vncserver restart

chmod +x ~/.vnc/xstartup
chkconfig vncserver on

cat >/etc/resolv.conf <<EOF
# Generated by NetworkManager
search myxnova.com
nameserver 8.8.8.8
nameserver 8.8.4.4


# No nameservers found; try putting DNS servers into your
# ifcfg files in /etc/sysconfig/network-scripts like so:
#
# DNS1=xxx.xxx.xxx.xxx
# DNS2=xxx.xxx.xxx.xxx
# DOMAIN=lab.foo.com bar.foo.com
EOF

wget -c http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
rpm -ivh rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
yum -y groupinstall "Development Tools" --setopt=protected_multilib=false
yum -y groupinstall "Chinese Support" --setopt=protected_multilib=false
yum -y groupinstall "Xfce" --setopt=protected_multilib=false
yum -y install "@Chinese Support" --setopt=protected_multilib=false
yum -y groupremove "Web Server" --setopt=protected_multilib=false
yum -y install xfce* tigervnc tigervnc-server firefox terminal filezilla --setopt=protected_multilib=false
yum -y install transmission* --setopt=protected_multilib=false

service vncserver stop

cat >/etc/sysconfig/i18n <<EOF
LANG="zh_TW.UTF-8"
SUPPORTED="zh_TW.UTF-8:zh_TW.Big5:zh_TW:zh:en_US.UTF-8:en_US:en"
SYSFONT=latarcyrheb-sun16
EOF

source /etc/sysconfig/i18n
service vncserver start

yum -y update --setopt=protected_multilib=false

iptables -I INPUT -p tcp --dport 5901 -j ACCEPT
iptables -I INPUT -p tcp --dport 25565 -j ACCEPT
iptables -I INPUT -p tcp --dport 25566 -j ACCEPT
iptables -I INPUT -p tcp --dport 8123 -j ACCEPT
service iptables save
service iptables restart

echo "Use VNC Client to connect Desktop"
echo "IP:5901 and your password"
echo "DONE!"
